- name: Get Prediction Server ec2
  ec2_remote_facts:
    filters:
      instance-state-name: running
      "tag:Name": "{{ prediction_server.name }}"
  register: ec2_info

- name: Add hosts to serverhost
  add_host: hostname="{{ item.public_dns_name }}"
            ansible_python_interpreter=python
            ansible_ssh_private_key_file=~/.ssh/{{ keypair_regst.key.name }}.pem
            ansible_ssh_user="{{ ec2.user }}"
            groupname="{{ prediction_server.host_group_name }}"
  with_items: "{{ ec2_info.instances }}"

- name: Set private dns name in variable
  set_fact:
    server_private_dns_name: "{{ item.private_dns_name }}"
  with_items: "{{ ec2_info.instances }}"

- name: Create Security Group
  ec2_group:
    name: "{{ prediction_server.security_group_name }}"
    description: "DiskProphet Server Security Group"
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto:        "icmp"
        from_port:    "8" # icmp type, -1 = any type
        to_port:      "-1" # icmp subtype, -1 = any subtype
        cidr_ip:      "{{ vpc.cidr_block }}"
      - proto:        "tcp"
        from_port:    "22"
        to_port:      "22"
        cidr_ip:      "{{ prediction_server.ssh_access_ip }}"
      - proto:        "tcp"
        from_port:    "{{ prediction_server.influxdb_port }}"
        to_port:      "{{ prediction_server.influxdb_port }}"
        cidr_ip:      "0.0.0.0/0"
      - proto:        "tcp"
        from_port:    "{{ prediction_server.grafana_port }}"
        to_port:      "{{ prediction_server.grafana_port }}"
        cidr_ip:      "0.0.0.0/0"
      - proto:        "tcp"
        from_port:    "{{ prediction_server.prediction_server_port }}"
        to_port:      "{{ prediction_server.prediction_server_port }}"
        cidr_ip:      "0.0.0.0/0"
  when: ec2_info.instances|length == 0

- name: Create prediction_server_ec2 instance
  ec2:
    instance_tags:
      Name: "{{ prediction_server.name }}"
    key_name: "{{ keypair.name }}"
    instance_type: "{{ prediction_server.instance_type }}"
    image: "{{ prediction_server.image }}"
    wait: yes
    group: "{{ prediction_server.security_group_name }}"
    count: 1
    vpc_subnet_id: "{{ public_subnet_id }}"
    assign_public_ip: yes
  when: ec2_info.instances|length == 0
  register: new_ec2_info

#- debug: var=new_ec2_info
#  when: new_ec2_info | success

- name: Add new hosts to serverhost
  add_host: hostname="{{ item.public_dns_name }}"
            ansible_python_interpreter=python
            ansible_ssh_private_key_file=~/.ssh/"{{ keypair_regst.key.name }}".pem
            ansible_ssh_user={{ ec2.user }}
            groupname="{{ prediction_server.host_group_name }}"
  with_items: "{{ new_ec2_info.instances }}"
  when: new_ec2_info.changed

- name: Set private dns name in variable
  set_fact:
    server_private_dns_name: "{{ item.private_dns_name }}"
  with_items: "{{ new_ec2_info.instances }}"
  when: new_ec2_info.changed
