- name: Create VPC
  ec2_vpc_net:
    name: "{{ vpc.vpc_name }}"
    cidr_block: "{{ vpc.cidr_block }}"
    state: "present"
  register: vpc_regist

- name: Set VPC ID in variable
  set_fact:
    vpc_id: "{{ vpc_regist.vpc.id }}"

- name: Create Public Subnet
  ec2_vpc_subnet:
    state: "present"
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ vpc.public_subnet_cidr }}"
    az: "{{ vpc.region }}a"
    resource_tags:
      Name: "Public Subnet"
  register: public_subnet_regist

- name: Set Public Subnet ID in variable
  set_fact:
    public_subnet_id: "{{ public_subnet_regist.subnet.id }}"

- name: Create Internet Gateway for VPC
  ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
    state: "present"
  register: vpc_igw_regist

- name: Set Internet Gateway ID in variable
  set_fact:
    igw_id: "{{ vpc_igw_regist.gateway_id }}"

- name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    tags:
      Name: "Public"
    subnets:
      - "{{ public_subnet_id }}"
    routes:
      - dest: "0.0.0.0/0"
        gateway_id: "{{ igw_id }}"